name: Publish API doc

on:
  push:
    branches:
      - main
    paths:
      - 'openapi.yml'

jobs:
  publish-api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4

      - name: Generate API doc
        run: npx @redocly/cli build-docs ./openapi.yml -o docs/api.html

      - name: Publish API doc
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b gh-pages
          git add -f ./docs/api.html
          git commit -m "publish api doc"
          git push -f -uorigin gh-pages

  