name: Wait Approve Test

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Start Message
        run: echo "Start!"

  wait-approve-test:
    runs-on: ubuntu-latest
    environment: wait-approve-test
    steps:
      - name: Echo Wait Approve Test Message
        run: echo "Approved!"

  execute-if-success:
    needs: wait-approve-test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Execute If Success Message
        run: echo "Execute If Success!"

  execute-if-failure:
    needs: wait-approve-test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Execute If Failure Message
        run: echo "Execute If Failure!"
  
  execute-if-cancelled:
    needs: wait-approve-test
    if: ${{ cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Execute If Cancelled Message
        run: echo "Execute If Cancelled!"

  execute-if-not-cancelled:
    needs: wait-approve-test
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Execute If Not Cancelled Message
        run: echo "Execute If Not Cancelled!"

  